import { Store, Deal } from '../shared/types';

export const SEED_STORES: Store[] = [
  {
    id: 'store-sharma-snacks',
    ownerId: 'merchant-sharma',
    name: 'Sharma Snacks & Chaat',
    category: 'SNACKS',
    streetAddress: 'Shop 14, FC Road, Shivajinagar, Pune',
    latitude: 18.5245,
    longitude: 73.8580,
    phoneContact: '+91 98220 11223',
    isActive: true,
    openingHours: '08:00 AM - 10:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    createdAt: new Date(Date.now() - 30 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-ganesh-panipuri',
    ownerId: 'merchant-ganesh',
    name: 'Ganesh Pani Puri & Fast Food',
    category: 'SNACKS',
    streetAddress: 'Corner Stall 3, Model Colony, Pune',
    latitude: 18.5280,
    longitude: 73.8590,
    phoneContact: '+91 98225 33445',
    isActive: true,
    openingHours: '02:00 PM - 10:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    createdAt: new Date(Date.now() - 28 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-abc-bakery',
    ownerId: 'merchant-abc',
    name: 'ABC Gourmet Bakery & Café',
    category: 'BAKERY',
    streetAddress: 'Plot 42, Fergusson College Rd, Shivajinagar, Pune',
    latitude: 18.5255,
    longitude: 73.8595,
    phoneContact: '+91 98230 12345',
    isActive: true,
    openingHours: '08:00 AM - 10:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    createdAt: new Date(Date.now() - 30 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-gokul-dairy',
    ownerId: 'merchant-gokul',
    name: 'Gokul Organic Dairy & Farm Fresh',
    category: 'DAIRY',
    streetAddress: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
    latitude: 18.5220,
    longitude: 73.8540,
    phoneContact: '+91 98221 44556',
    isActive: true,
    openingHours: '06:00 AM - 09:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    createdAt: new Date(Date.now() - 25 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-shivaji-vadapav',
    ownerId: 'merchant-shivaji',
    name: 'Shivaji Vada Pav Corner',
    category: 'SNACKS',
    streetAddress: 'Opposite Garware College, Karve Road, Pune',
    latitude: 18.5140,
    longitude: 73.8400,
    phoneContact: '+91 98233 77889',
    isActive: true,
    openingHours: '09:00 AM - 09:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    createdAt: new Date(Date.now() - 20 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-xyz-pizzeria',
    ownerId: 'merchant-xyz',
    name: 'XYZ Campus Pizzeria & Deli',
    category: 'RESTAURANT',
    streetAddress: '12 University Circle, Model Colony, Pune',
    latitude: 18.5298,
    longitude: 73.8652,
    phoneContact: '+91 98220 54321',
    isActive: true,
    openingHours: '11:00 AM - 11:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    createdAt: new Date(Date.now() - 20 * 24 * 3600000).toISOString(),
  }
];

export function getInitialDeals(): Deal[] {
  const now = Date.now();

  return [
    {
      id: 'deal-samosa-sharma',
      storeId: 'store-sharma-snacks',
      storeName: 'Sharma Snacks',
      storeCategory: 'Snacks',
      storeAddress: 'Shop 14, FC Road, Shivajinagar, Pune',
      latitude: 18.5245,
      longitude: 73.8580,
      phoneContact: '+91 98220 11223',
      productName: 'Hot Crispy Punjabi Samosa (Set of 4)',
      category: 'Snacks',
      initialUnits: 20,
      remainingUnits: 12,
      soldUnits: 8,
      unit: 'pieces',
      originalPrice: 80,
      recommendedPrice: 48,
      publishedPrice: 48,
      wasteRiskScore: 78,
      wasteRiskPercentage: 78,
      salesVelocity: 'MEDIUM',
      salesVelocityNumeric: 2.5,
      manufacturingDate: '2026-09-11',
      manufacturingTime: '10:00 AM',
      hasManufacturingTime: true,
      manufacturingDateFormatted: '11 September 2026, 10:00 AM',
      expiryDate: '2026-09-11',
      expiryTime: '08:00 PM',
      hasExpiryTime: true,
      expiryDateFormatted: '11 September 2026, 8:00 PM',
      expiryCountdownFormatted: '4h 32m left',
      deadline: new Date(now + 4.5 * 3600000).toISOString(),
      status: 'ACTIVE',
      discountPct: 40,
      freshnessTag: 'Fresh Batch',
      description: 'Crispy golden potato-peas stuffed samosas served with sweet tamarind and spicy mint chutneys.',
      imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 2 * 3600000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },
    {
      id: 'deal-panipuri-ganesh',
      storeId: 'store-ganesh-panipuri',
      storeName: 'Ganesh Pani Puri',
      storeCategory: 'Snacks',
      storeAddress: 'Corner Stall 3, Model Colony, Pune',
      latitude: 18.5280,
      longitude: 73.8590,
      phoneContact: '+91 98225 33445',
      productName: 'Pani Puri Combo Kit (30 Puris + 2 Flavored Waters)',
      category: 'Snacks',
      initialUnits: 15,
      remainingUnits: 6,
      soldUnits: 9,
      unit: 'packs',
      originalPrice: 120,
      recommendedPrice: 60,
      publishedPrice: 60,
      wasteRiskScore: 82,
      wasteRiskPercentage: 82,
      salesVelocity: 'HIGH',
      salesVelocityNumeric: 3.5,
      manufacturingDate: '2026-09-11',
      manufacturingTime: '11:30 AM',
      hasManufacturingTime: true,
      manufacturingDateFormatted: '11 September 2026, 11:30 AM',
      expiryDate: '2026-09-11',
      expiryTime: '09:00 PM',
      hasExpiryTime: true,
      expiryDateFormatted: '11 September 2026, 9:00 PM',
      expiryCountdownFormatted: '5h 15m left',
      deadline: new Date(now + 5.25 * 3600000).toISOString(),
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Freshly Prepared',
      description: 'Crispy semolina puris with spicy hing mint water and sweet date chutney with ragda.',
      imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 3 * 3600000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-vadapav-shivaji',
      storeId: 'store-shivaji-vadapav',
      storeName: 'Shivaji Vada Pav',
      storeCategory: 'Snacks',
      storeAddress: 'Opposite Garware College, Karve Road, Pune',
      latitude: 18.5140,
      longitude: 73.8400,
      phoneContact: '+91 98233 77889',
      productName: 'Butter Vada Pav with Fried Chutney (Pair)',
      category: 'Snacks',
      initialUnits: 25,
      remainingUnits: 14,
      soldUnits: 11,
      unit: 'pieces',
      originalPrice: 50,
      recommendedPrice: 30,
      publishedPrice: 30,
      wasteRiskScore: 70,
      wasteRiskPercentage: 70,
      salesVelocity: 'HIGH',
      salesVelocityNumeric: 4.0,
      manufacturingDate: '2026-09-11',
      hasManufacturingTime: false,
      manufacturingDateFormatted: '11 September 2026',
      expiryDate: '2026-09-11',
      hasExpiryTime: false,
      expiryDateFormatted: '11 September 2026',
      expiryCountdownFormatted: '6h 45m left',
      deadline: new Date(now + 6.75 * 3600000).toISOString(),
      status: 'ACTIVE',
      discountPct: 40,
      freshnessTag: 'Hot Batch',
      description: 'Spiced potato batata vada tucked inside fresh pav bread with garlic dry chutney.',
      imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 1 * 3600000).toISOString(),
      updatedAt: new Date(now - 15 * 60000).toISOString(),
    },
    {
      id: 'deal-fresh-sandwich-canonical',
      storeId: 'store-abc-bakery',
      storeName: 'ABC Gourmet Bakery & Café',
      storeCategory: 'Bakery',
      storeAddress: 'Plot 42, Fergusson College Rd, Shivajinagar, Pune',
      latitude: 18.5255,
      longitude: 73.8595,
      phoneContact: '+91 98230 12345',
      productName: 'Fresh Sandwich',
      category: 'Prepared Food',
      initialUnits: 15,
      remainingUnits: 8,
      soldUnits: 7,
      unit: 'pieces',
      originalPrice: 60,
      recommendedPrice: 35,
      publishedPrice: 35,
      wasteRiskScore: 86,
      wasteRiskPercentage: 86,
      salesVelocity: 'LOW',
      salesVelocityNumeric: 1.5,
      manufacturingDate: '2026-09-10',
      hasManufacturingTime: false,
      manufacturingDateFormatted: '10 September 2026',
      expiryDate: '2026-09-12',
      hasExpiryTime: false,
      expiryDateFormatted: '12 September 2026',
      expiryCountdownFormatted: '1 day left',
      deadline: new Date(now + 28 * 3600000).toISOString(),
      status: 'ACTIVE',
      discountPct: 42,
      freshnessTag: 'Freshly Assembled',
      description: 'Triple decker multigrain bread, garden lettuce, cucumber, cheddar cheese, and fresh herb spread.',
      imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 4 * 3600000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-dairy-paneer-1',
      storeId: 'store-gokul-dairy',
      storeName: 'Gokul Organic Dairy & Farm Fresh',
      storeCategory: 'Dairy',
      storeAddress: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
      latitude: 18.5220,
      longitude: 73.8540,
      phoneContact: '+91 98221 44556',
      productName: 'Fresh Organic Malai Paneer (500g Block)',
      category: 'Dairy',
      initialUnits: 12,
      remainingUnits: 10,
      soldUnits: 2,
      unit: 'packs',
      originalPrice: 220,
      recommendedPrice: 110,
      publishedPrice: 110,
      wasteRiskScore: 74,
      wasteRiskPercentage: 74,
      salesVelocity: 'MEDIUM',
      salesVelocityNumeric: 2.0,
      manufacturingDate: '2026-09-10',
      hasManufacturingTime: false,
      manufacturingDateFormatted: '10 September 2026',
      expiryDate: '2026-09-13',
      hasExpiryTime: false,
      expiryDateFormatted: '13 September 2026',
      expiryCountdownFormatted: '2 days left',
      deadline: new Date(now + 52 * 3600000).toISOString(),
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Chilled Batch',
      description: 'Vacuum packed pure buffalo milk malai paneer. Made fresh, keep refrigerated.',
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 15 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },
    {
      id: 'deal-dairy-milk-2',
      storeId: 'store-gokul-dairy',
      storeName: 'Gokul Organic Dairy & Farm Fresh',
      storeCategory: 'Dairy',
      storeAddress: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
      latitude: 18.5220,
      longitude: 73.8540,
      phoneContact: '+91 98221 44556',
      productName: 'Pasteurized Whole Cow Milk (1L Pouch)',
      category: 'Dairy',
      initialUnits: 20,
      remainingUnits: 16,
      soldUnits: 4,
      unit: 'litres',
      originalPrice: 70,
      recommendedPrice: 45,
      publishedPrice: 45,
      wasteRiskScore: 68,
      wasteRiskPercentage: 68,
      salesVelocity: 'HIGH',
      salesVelocityNumeric: 4.5,
      manufacturingDate: '2026-09-11',
      manufacturingTime: '06:00 AM',
      hasManufacturingTime: true,
      manufacturingDateFormatted: '11 September 2026, 6:00 AM',
      expiryDate: '2026-09-12',
      expiryTime: '12:00 PM',
      hasExpiryTime: true,
      expiryDateFormatted: '12 September 2026, 12:00 PM',
      expiryCountdownFormatted: '18h 20m left',
      deadline: new Date(now + 18.3 * 3600000).toISOString(),
      status: 'ACTIVE',
      discountPct: 36,
      freshnessTag: 'Verified Fresh',
      description: 'Full cream pasteurized fresh cow milk, rich in calcium and natural protein.',
      imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 25 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-sourdough-1',
      storeId: 'store-abc-bakery',
      storeName: 'ABC Gourmet Bakery & Café',
      storeCategory: 'Bakery',
      storeAddress: 'Plot 42, Fergusson College Rd, Shivajinagar, Pune',
      latitude: 18.5255,
      longitude: 73.8595,
      phoneContact: '+91 98230 12345',
      productName: 'Artisan Sourdough Loaf',
      category: 'Bakery',
      initialUnits: 15,
      remainingUnits: 12,
      soldUnits: 3,
      unit: 'pieces',
      originalPrice: 120,
      recommendedPrice: 60,
      publishedPrice: 60,
      wasteRiskScore: 78,
      wasteRiskPercentage: 78,
      salesVelocity: 'LOW',
      salesVelocityNumeric: 1.0,
      manufacturingDate: '2026-09-10',
      hasManufacturingTime: false,
      manufacturingDateFormatted: '10 September 2026',
      expiryDate: '2026-09-12',
      hasExpiryTime: false,
      expiryDateFormatted: '12 September 2026',
      expiryCountdownFormatted: '1 day left',
      deadline: new Date(now + 26 * 3600000).toISOString(),
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Verified Fresh',
      description: 'Slow-fermented artisan rustic sourdough loaf. Baked fresh, crusty outside, airy inside.',
      imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 10 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-margherita-3',
      storeId: 'store-xyz-pizzeria',
      storeName: 'XYZ Campus Pizzeria & Deli',
      storeCategory: 'Prepared Food',
      storeAddress: '12 University Circle, Model Colony, Pune',
      latitude: 18.5298,
      longitude: 73.8652,
      phoneContact: '+91 98220 54321',
      productName: 'Margherita Pizza Slice Duo',
      category: 'Prepared Food',
      initialUnits: 8,
      remainingUnits: 5,
      soldUnits: 3,
      unit: 'portions',
      originalPrice: 150,
      recommendedPrice: 90,
      publishedPrice: 90,
      wasteRiskScore: 64,
      wasteRiskPercentage: 64,
      salesVelocity: 'MEDIUM',
      salesVelocityNumeric: 2.5,
      manufacturingDate: '2026-09-11',
      manufacturingTime: '01:00 PM',
      hasManufacturingTime: true,
      manufacturingDateFormatted: '11 September 2026, 1:00 PM',
      expiryDate: '2026-09-11',
      expiryTime: '10:00 PM',
      hasExpiryTime: true,
      expiryDateFormatted: '11 September 2026, 10:00 PM',
      expiryCountdownFormatted: '7h 10m left',
      deadline: new Date(now + 7.15 * 3600000).toISOString(),
      status: 'ACTIVE',
      discountPct: 40,
      freshnessTag: 'Warm Batch',
      description: 'Fresh San Marzano tomato base, buffalo mozzarella, and sweet garden basil.',
      imageUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 30 * 60000).toISOString(),
      updatedAt: new Date(now - 12 * 60000).toISOString(),
    }
  ];
}