import { Store, Deal } from '../shared/types';

export const SEED_STORES: Store[] = [
  // Pune Central Outlets
  {
    id: 'store-abc-bakery',
    ownerId: 'merchant-abc',
    name: 'ABC Gourmet Bakery & Café',
    category: 'BAKERY',
    streetAddress: 'Plot 42, Fergusson College Rd, Shivajinagar, Pune',
    latitude: 18.5255,
    longitude: 73.8595,
    phoneContact: '+91 98230 12345',
    isActive: true,
    openingHours: '08:00 AM - 10:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    createdAt: new Date(Date.now() - 30 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-gokul-dairy',
    ownerId: 'merchant-gokul',
    name: 'Gokul Organic Dairy & Farm Fresh',
    category: 'DAIRY',
    streetAddress: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
    latitude: 18.5220,
    longitude: 73.8540,
    phoneContact: '+91 98221 44556',
    isActive: true,
    openingHours: '06:00 AM - 09:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    createdAt: new Date(Date.now() - 25 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-xyz-pizzeria',
    ownerId: 'merchant-xyz',
    name: 'XYZ Campus Pizzeria & Deli',
    category: 'RESTAURANT',
    streetAddress: '12 University Circle, Model Colony, Pune',
    latitude: 18.5298,
    longitude: 73.8652,
    phoneContact: '+91 98220 54321',
    isActive: true,
    openingHours: '11:00 AM - 11:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    createdAt: new Date(Date.now() - 20 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-green-canteen',
    ownerId: 'merchant-canteen',
    name: 'The Green Campus Canteen',
    category: 'CANTEEN',
    streetAddress: 'MIT-WPU Quadrangle, Kothrud, Pune',
    latitude: 18.5160,
    longitude: 73.8505,
    phoneContact: '+91 98210 99887',
    isActive: true,
    openingHours: '07:30 AM - 09:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    createdAt: new Date(Date.now() - 15 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-bean-brew',
    ownerId: 'merchant-bean',
    name: 'Bean & Brew Artisanal Coffee Bar',
    category: 'CAFE',
    streetAddress: '5 Lane 7, Koregaon Park, Pune',
    latitude: 18.5340,
    longitude: 73.8610,
    phoneContact: '+91 98290 66778',
    isActive: true,
    openingHours: '08:00 AM - 11:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    createdAt: new Date(Date.now() - 10 * 24 * 3600000).toISOString(),
  },
  {
    id: 'store-freshmart',
    ownerId: 'merchant-fresh',
    name: 'FreshMart Super Grocers',
    category: 'GROCERY',
    streetAddress: 'Shop 3, Deccan Gymkhana, Pune',
    latitude: 18.5130,
    longitude: 73.8420,
    phoneContact: '+91 98244 33221',
    isActive: true,
    openingHours: '07:00 AM - 10:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=600&auto=format&fit=crop&q=80',
    rating: 4.4,
    createdAt: new Date(Date.now() - 5 * 24 * 3600000).toISOString(),
  },

  // NARHE, PUNE OUTLETS
  {
    id: 'store-shivani-dairy',
    ownerId: 'merchant-shivani',
    name: 'Shivani Dairy & Sweets',
    category: 'DAIRY',
    streetAddress: 'Navale Bridge Road, Narhe, Pune',
    latitude: 18.4485,
    longitude: 73.8266,
    phoneContact: '+91 98231 11223',
    isActive: true,
    openingHours: '06:00 AM - 10:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-navale-bakehouse',
    ownerId: 'merchant-navale',
    name: 'Navale Bakehouse',
    category: 'BAKERY',
    streetAddress: 'JSPM Circle, Narhe, Pune',
    latitude: 18.4490,
    longitude: 73.8270,
    phoneContact: '+91 98232 22334',
    isActive: true,
    openingHours: '07:00 AM - 10:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-jspm-canteen',
    ownerId: 'merchant-jspm',
    name: 'JSPM Canteen Surplus',
    category: 'CANTEEN',
    streetAddress: 'JSPM Campus Quadrangle, Narhe, Pune',
    latitude: 18.4500,
    longitude: 73.8280,
    phoneContact: '+91 98233 33445',
    isActive: true,
    openingHours: '08:00 AM - 08:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    createdAt: new Date().toISOString(),
  },

  // ALANDI, PUNE OUTLETS
  {
    id: 'store-mahesh-milk',
    ownerId: 'merchant-mahesh',
    name: 'Mahesh Milk Center & Creamery',
    category: 'DAIRY',
    streetAddress: 'Temple Road, Alandi, Pune',
    latitude: 18.6750,
    longitude: 73.8986,
    phoneContact: '+91 98234 44556',
    isActive: true,
    openingHours: '06:00 AM - 09:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-indrayani-sweets',
    ownerId: 'merchant-indrayani',
    name: 'Indrayani Sweets & Bakers',
    category: 'BAKERY',
    streetAddress: 'Indrayani River Ghat, Alandi, Pune',
    latitude: 18.6760,
    longitude: 73.8990,
    phoneContact: '+91 98235 55667',
    isActive: true,
    openingHours: '07:30 AM - 10:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    createdAt: new Date().toISOString(),
  },

  // MUMBAI OUTLETS (Dadar & Bandra)
  {
    id: 'store-dadar-dairy',
    ownerId: 'merchant-dadar',
    name: 'Dadar Local Dairy',
    category: 'DAIRY',
    streetAddress: 'Ranade Road, Dadar West, Mumbai',
    latitude: 19.0178,
    longitude: 72.8478,
    phoneContact: '+91 98200 11223',
    isActive: true,
    openingHours: '06:00 AM - 09:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-bandra-bakery',
    ownerId: 'merchant-bandra',
    name: 'Bandra Artisan Bakery',
    category: 'BAKERY',
    streetAddress: 'Hill Road, Bandra West, Mumbai',
    latitude: 19.0596,
    longitude: 72.8295,
    phoneContact: '+91 98201 22334',
    isActive: true,
    openingHours: '08:00 AM - 11:00 PM',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'store-suburban-tiffin',
    ownerId: 'merchant-tiffin',
    name: 'Suburban Tiffin Services',
    category: 'RESTAURANT',
    streetAddress: 'Linking Road, Bandra West, Mumbai',
    latitude: 19.0610,
    longitude: 72.8310,
    phoneContact: '+91 98202 33445',
    isActive: true,
    openingHours: '11:00 AM - 10:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    createdAt: new Date().toISOString(),
  }
];

export function getInitialDeals(): Deal[] {
  const now = Date.now();
  return [
    // ───────────── NARHE, PUNE DEALS ─────────────
    {
      id: 'deal-narhe-curd-1',
      storeId: 'store-shivani-dairy',
      storeName: 'Shivani Dairy & Sweets',
      shopName: 'Shivani Dairy & Sweets',
      storeCategory: 'DAIRY',
      storeAddress: 'Navale Bridge Road, Narhe, Pune',
      locationName: 'Navale Bridge Road, Narhe, Pune',
      latitude: 18.4485,
      longitude: 73.8266,
      phoneContact: '+91 98231 11223',
      productName: 'Fresh Curd / Dahi (500g Pouch)',
      title: 'Fresh Curd / Dahi (500g Pouch)',
      category: 'DAIRY',
      initialUnits: 15,
      remainingUnits: 12,
      soldUnits: 3,
      originalPrice: 40,
      recommendedPrice: 20,
      publishedPrice: 20,
      discountedPrice: 20,
      wasteRiskScore: 76,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 90 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 9:00 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Chilled Batch',
      description: 'Chilled fresh set dahi prepared from pure farm milk. Packaged today morning.',
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 20 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },
    {
      id: 'deal-narhe-sourdough-2',
      storeId: 'store-navale-bakehouse',
      storeName: 'Navale Bakehouse',
      shopName: 'Navale Bakehouse',
      storeCategory: 'BAKERY',
      storeAddress: 'JSPM Circle, Narhe, Pune',
      locationName: 'JSPM Circle, Narhe, Pune',
      latitude: 18.4490,
      longitude: 73.8270,
      phoneContact: '+91 98232 22334',
      productName: 'Whole Wheat Sourdough Loaf',
      title: 'Whole Wheat Sourdough Loaf',
      category: 'BAKERY',
      initialUnits: 10,
      remainingUnits: 8,
      soldUnits: 2,
      originalPrice: 120,
      recommendedPrice: 60,
      publishedPrice: 60,
      discountedPrice: 60,
      wasteRiskScore: 72,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 120 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 7:00 PM - 10:00 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Verified Fresh',
      description: 'Artisan sourdough loaf baked with 100% stone-ground whole wheat.',
      imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 30 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-narhe-thali-3',
      storeId: 'store-jspm-canteen',
      storeName: 'JSPM Canteen Surplus',
      shopName: 'JSPM Canteen Surplus',
      storeCategory: 'CANTEEN',
      storeAddress: 'JSPM Campus Quadrangle, Narhe, Pune',
      locationName: 'JSPM Campus Quadrangle, Narhe, Pune',
      latitude: 18.4500,
      longitude: 73.8280,
      phoneContact: '+91 98233 33445',
      productName: 'Veg Thali Batch & Rice Combo',
      title: 'Veg Thali Batch & Rice Combo',
      category: 'CANTEEN',
      initialUnits: 20,
      remainingUnits: 15,
      soldUnits: 5,
      originalPrice: 100,
      recommendedPrice: 50,
      publishedPrice: 50,
      discountedPrice: 50,
      wasteRiskScore: 80,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 45 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 5:30 PM - 8:30 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Kitchen Fresh',
      description: 'Complete veg meal with 3 chapatis, paneer sabzi, dal fry, basmati rice, and salad.',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 15 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },
    {
      id: 'deal-narhe-milk-4',
      storeId: 'store-shivani-dairy',
      storeName: 'Shivani Dairy & Sweets',
      shopName: 'Shivani Dairy & Sweets',
      storeCategory: 'DAIRY',
      storeAddress: 'Navale Bridge Road, Narhe, Pune',
      locationName: 'Navale Bridge Road, Narhe, Pune',
      latitude: 18.4485,
      longitude: 73.8266,
      phoneContact: '+91 98231 11223',
      productName: 'Fresh Milk (1L Pouch)',
      title: 'Fresh Milk (1L Pouch)',
      category: 'DAIRY',
      initialUnits: 18,
      remainingUnits: 14,
      soldUnits: 4,
      originalPrice: 66,
      recommendedPrice: 35,
      publishedPrice: 35,
      discountedPrice: 35,
      wasteRiskScore: 70,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 80 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 9:30 PM',
      status: 'ACTIVE',
      discountPct: 47,
      freshnessTag: 'Farm Chilled',
      description: 'Pure whole cow milk sourced daily from regional farms near Narhe.',
      imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 25 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-narhe-sandwich-5',
      storeId: 'store-navale-bakehouse',
      storeName: 'Navale Bakehouse',
      shopName: 'Navale Bakehouse',
      storeCategory: 'BAKERY',
      storeAddress: 'JSPM Circle, Narhe, Pune',
      locationName: 'JSPM Circle, Narhe, Pune',
      latitude: 18.4490,
      longitude: 73.8270,
      phoneContact: '+91 98232 22334',
      productName: 'Gourmet Sandwich Combo Pack',
      title: 'Gourmet Sandwich Combo Pack',
      category: 'BAKERY',
      initialUnits: 12,
      remainingUnits: 9,
      soldUnits: 3,
      originalPrice: 110,
      recommendedPrice: 55,
      publishedPrice: 55,
      discountedPrice: 55,
      wasteRiskScore: 65,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 100 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:30 PM - 9:30 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Freshly Assembled',
      description: 'Fresh grilled cheese veggie club sandwich with seasoned potato crisps.',
      imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 20 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },

    // ───────────── ALANDI, PUNE DEALS ─────────────
    {
      id: 'deal-alandi-milk-1',
      storeId: 'store-mahesh-milk',
      storeName: 'Mahesh Milk Center & Creamery',
      shopName: 'Mahesh Milk Center & Creamery',
      storeCategory: 'DAIRY',
      storeAddress: 'Temple Road, Alandi, Pune',
      locationName: 'Temple Road, Alandi, Pune',
      latitude: 18.6750,
      longitude: 73.8986,
      phoneContact: '+91 98234 44556',
      productName: 'Pure Buffalo Milk (1L Pouch)',
      title: 'Pure Buffalo Milk (1L Pouch)',
      category: 'DAIRY',
      initialUnits: 25,
      remainingUnits: 18,
      soldUnits: 7,
      originalPrice: 70,
      recommendedPrice: 40,
      publishedPrice: 40,
      discountedPrice: 40,
      wasteRiskScore: 70,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 60 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - End of Day',
      status: 'ACTIVE',
      discountPct: 43,
      freshnessTag: 'Verified Fresh',
      description: 'Fresh high-fat buffalo milk straight from rural Alandi farms. Keep chilled.',
      imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 25 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-alandi-pastry-2',
      storeId: 'store-indrayani-sweets',
      storeName: 'Indrayani Sweets & Bakers',
      shopName: 'Indrayani Sweets & Bakers',
      storeCategory: 'BAKERY',
      storeAddress: 'Indrayani River Ghat, Alandi, Pune',
      locationName: 'Indrayani River Ghat, Alandi, Pune',
      latitude: 18.6760,
      longitude: 73.8990,
      phoneContact: '+91 98235 55667',
      productName: 'Assorted Cream Rolls & Doughnuts',
      title: 'Assorted Cream Rolls & Doughnuts',
      category: 'BAKERY',
      initialUnits: 16,
      remainingUnits: 12,
      soldUnits: 4,
      originalPrice: 150,
      recommendedPrice: 75,
      publishedPrice: 75,
      discountedPrice: 75,
      wasteRiskScore: 65,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 100 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 7:00 PM - 10:00 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Freshly Baked',
      description: 'Freshly whipped vanilla cream rolls and glazed chocolate doughnuts.',
      imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 30 * 60000).toISOString(),
      updatedAt: new Date(now - 15 * 60000).toISOString(),
    },
    {
      id: 'deal-alandi-curd-3',
      storeId: 'store-mahesh-milk',
      storeName: 'Mahesh Milk Center & Creamery',
      shopName: 'Mahesh Milk Center & Creamery',
      storeCategory: 'DAIRY',
      storeAddress: 'Temple Road, Alandi, Pune',
      locationName: 'Temple Road, Alandi, Pune',
      latitude: 18.6750,
      longitude: 73.8986,
      phoneContact: '+91 98234 44556',
      productName: 'Fresh Curd / Dahi (500g Pouch)',
      title: 'Fresh Curd / Dahi (500g Pouch)',
      category: 'DAIRY',
      initialUnits: 14,
      remainingUnits: 10,
      soldUnits: 4,
      originalPrice: 44,
      recommendedPrice: 25,
      publishedPrice: 25,
      discountedPrice: 25,
      wasteRiskScore: 68,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 75 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 9:30 PM',
      status: 'ACTIVE',
      discountPct: 43,
      freshnessTag: 'Chilled Batch',
      description: 'Thick organic set curd prepared in traditional clay vessels.',
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 20 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },

    // ───────────── MUMBAI DEALS (DADAR & BANDRA) ─────────────
    {
      id: 'deal-mumbai-paneer-1',
      storeId: 'store-dadar-dairy',
      storeName: 'Dadar Local Dairy',
      shopName: 'Dadar Local Dairy',
      storeCategory: 'DAIRY',
      storeAddress: 'Ranade Road, Dadar West, Mumbai',
      locationName: 'Ranade Road, Dadar West, Mumbai',
      latitude: 19.0178,
      longitude: 72.8478,
      phoneContact: '+91 98200 11223',
      productName: 'Fresh Malai Paneer (250g Block)',
      title: 'Fresh Malai Paneer (250g Block)',
      category: 'DAIRY',
      initialUnits: 14,
      remainingUnits: 10,
      soldUnits: 4,
      originalPrice: 110,
      recommendedPrice: 60,
      publishedPrice: 60,
      discountedPrice: 60,
      wasteRiskScore: 75,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 55 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 5:30 PM - 9:00 PM',
      status: 'ACTIVE',
      discountPct: 45,
      freshnessTag: 'Chilled & Fresh',
      description: 'Soft, rich cottage cheese made fresh daily in Dadar creamery.',
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 20 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },
    {
      id: 'deal-mumbai-croissant-2',
      storeId: 'store-bandra-bakery',
      storeName: 'Bandra Artisan Bakery',
      shopName: 'Bandra Artisan Bakery',
      storeCategory: 'BAKERY',
      storeAddress: 'Hill Road, Bandra West, Mumbai',
      locationName: 'Hill Road, Bandra West, Mumbai',
      latitude: 19.0596,
      longitude: 72.8295,
      phoneContact: '+91 98201 22334',
      productName: 'Butter Croissant Pair',
      title: 'Butter Croissant Pair',
      category: 'BAKERY',
      initialUnits: 12,
      remainingUnits: 9,
      soldUnits: 3,
      originalPrice: 200,
      recommendedPrice: 100,
      publishedPrice: 100,
      discountedPrice: 100,
      wasteRiskScore: 68,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 90 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 10:00 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Verified Fresh',
      description: 'Flaky French butter croissants baked fresh at Hill Road bakery.',
      imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 35 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-mumbai-paneer-masala-3',
      storeId: 'store-suburban-tiffin',
      storeName: 'Suburban Tiffin Services',
      shopName: 'Suburban Tiffin Services',
      storeCategory: 'RESTAURANT',
      storeAddress: 'Linking Road, Bandra West, Mumbai',
      locationName: 'Linking Road, Bandra West, Mumbai',
      latitude: 19.0610,
      longitude: 72.8310,
      phoneContact: '+91 98202 33445',
      productName: 'Paneer Butter Masala Pack & Rotis',
      title: 'Paneer Butter Masala Pack & Rotis',
      category: 'RESTAURANT',
      initialUnits: 15,
      remainingUnits: 11,
      soldUnits: 4,
      originalPrice: 180,
      recommendedPrice: 90,
      publishedPrice: 90,
      discountedPrice: 90,
      wasteRiskScore: 74,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 50 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 9:30 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Kitchen Hot',
      description: 'Rich North Indian cottage cheese gravy with 4 butter phulkas.',
      imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 15 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },
    {
      id: 'deal-mumbai-biryani-4',
      storeId: 'store-suburban-tiffin',
      storeName: 'Suburban Tiffin Services',
      shopName: 'Suburban Tiffin Services',
      storeCategory: 'RESTAURANT',
      storeAddress: 'Linking Road, Bandra West, Mumbai',
      locationName: 'Linking Road, Bandra West, Mumbai',
      latitude: 19.0610,
      longitude: 72.8310,
      phoneContact: '+91 98202 33445',
      productName: 'Veg Biryani Handi (Single Portion)',
      title: 'Veg Biryani Handi (Single Portion)',
      category: 'RESTAURANT',
      initialUnits: 10,
      remainingUnits: 7,
      soldUnits: 3,
      originalPrice: 160,
      recommendedPrice: 85,
      publishedPrice: 85,
      discountedPrice: 85,
      wasteRiskScore: 72,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 65 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:30 PM - 9:30 PM',
      status: 'ACTIVE',
      discountPct: 47,
      freshnessTag: 'Kitchen Fresh',
      description: 'Aromatic dum veg biryani cooked with saffron, long-grain basmati, and raita.',
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 25 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-mumbai-sourdough-5',
      storeId: 'store-bandra-bakery',
      storeName: 'Bandra Artisan Bakery',
      shopName: 'Bandra Artisan Bakery',
      storeCategory: 'BAKERY',
      storeAddress: 'Hill Road, Bandra West, Mumbai',
      locationName: 'Hill Road, Bandra West, Mumbai',
      latitude: 19.0596,
      longitude: 72.8295,
      phoneContact: '+91 98201 22334',
      productName: 'Country Sourdough Bread Loaf',
      title: 'Country Sourdough Bread Loaf',
      category: 'BAKERY',
      initialUnits: 10,
      remainingUnits: 8,
      soldUnits: 2,
      originalPrice: 150,
      recommendedPrice: 75,
      publishedPrice: 75,
      discountedPrice: 75,
      wasteRiskScore: 66,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 110 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 10:30 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Oven Fresh',
      description: 'Traditional sourdough with crispy crust and light airy crumb.',
      imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 30 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-mumbai-dahi-6',
      storeId: 'store-dadar-dairy',
      storeName: 'Dadar Local Dairy',
      shopName: 'Dadar Local Dairy',
      storeCategory: 'DAIRY',
      storeAddress: 'Ranade Road, Dadar West, Mumbai',
      locationName: 'Ranade Road, Dadar West, Mumbai',
      latitude: 19.0178,
      longitude: 72.8478,
      phoneContact: '+91 98200 11223',
      productName: 'Fresh Curd / Dahi (500g Pack)',
      title: 'Fresh Curd / Dahi (500g Pack)',
      category: 'DAIRY',
      initialUnits: 15,
      remainingUnits: 11,
      soldUnits: 4,
      originalPrice: 50,
      recommendedPrice: 30,
      publishedPrice: 30,
      discountedPrice: 30,
      wasteRiskScore: 70,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 85 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 9:30 PM',
      status: 'ACTIVE',
      discountPct: 40,
      freshnessTag: 'Chilled Batch',
      description: 'Authentic Mumbai local dairy fresh dahi pouch.',
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 20 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },

    // ───────────── PUNE CENTRAL DEALS ─────────────
    {
      id: 'deal-dairy-paneer-1',
      storeId: 'store-gokul-dairy',
      storeName: 'Gokul Organic Dairy & Farm Fresh',
      shopName: 'Gokul Organic Dairy & Farm Fresh',
      storeCategory: 'DAIRY',
      storeAddress: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
      locationName: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
      latitude: 18.5220,
      longitude: 73.8540,
      phoneContact: '+91 98221 44556',
      productName: 'Fresh Organic Malai Paneer (500g Block)',
      title: 'Fresh Organic Malai Paneer (500g Block)',
      category: 'DAIRY',
      initialUnits: 12,
      remainingUnits: 10,
      soldUnits: 2,
      originalPrice: 220,
      recommendedPrice: 110,
      publishedPrice: 110,
      discountedPrice: 110,
      wasteRiskScore: 74,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 45 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 5:00 PM - 8:30 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Chilled Batch',
      description: 'Vacuum packed pure buffalo milk malai paneer. Made fresh today morning, keep refrigerated.',
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 15 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },
    {
      id: 'deal-dairy-milk-2',
      storeId: 'store-gokul-dairy',
      storeName: 'Gokul Organic Dairy & Farm Fresh',
      shopName: 'Gokul Organic Dairy & Farm Fresh',
      storeCategory: 'DAIRY',
      storeAddress: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
      locationName: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
      latitude: 18.5220,
      longitude: 73.8540,
      phoneContact: '+91 98221 44556',
      productName: 'Pasteurized Whole Cow Milk (1L Pouch)',
      title: 'Pasteurized Whole Cow Milk (1L Pouch)',
      category: 'DAIRY',
      initialUnits: 20,
      remainingUnits: 16,
      soldUnits: 4,
      originalPrice: 70,
      recommendedPrice: 45,
      publishedPrice: 45,
      discountedPrice: 45,
      wasteRiskScore: 68,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 60 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 9:00 PM',
      status: 'ACTIVE',
      discountPct: 36,
      freshnessTag: 'Verified Fresh',
      description: 'Full cream pasteurized fresh cow milk, rich in calcium and natural protein.',
      imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 25 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-dairy-yogurt-3',
      storeId: 'store-gokul-dairy',
      storeName: 'Gokul Organic Dairy & Farm Fresh',
      shopName: 'Gokul Organic Dairy & Farm Fresh',
      storeCategory: 'DAIRY',
      storeAddress: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
      locationName: 'Shop 8, Jangali Maharaj Rd, Deccan, Pune',
      latitude: 18.5220,
      longitude: 73.8540,
      phoneContact: '+91 98221 44556',
      productName: 'Artisanal Set Dahi / Greek Yogurt (400g)',
      title: 'Artisanal Set Dahi / Greek Yogurt (400g)',
      category: 'DAIRY',
      initialUnits: 10,
      remainingUnits: 8,
      soldUnits: 2,
      originalPrice: 120,
      recommendedPrice: 65,
      publishedPrice: 65,
      discountedPrice: 65,
      wasteRiskScore: 62,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 90 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:30 PM - 9:30 PM',
      status: 'ACTIVE',
      discountPct: 46,
      freshnessTag: 'Sealed Fresh',
      description: 'Thick probiotic natural curd prepared from pure unadulterated farm milk.',
      imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 30 * 60000).toISOString(),
      updatedAt: new Date(now - 12 * 60000).toISOString(),
    },
    {
      id: 'deal-sourdough-1',
      storeId: 'store-abc-bakery',
      storeName: 'ABC Gourmet Bakery & Café',
      shopName: 'ABC Gourmet Bakery & Café',
      storeCategory: 'BAKERY',
      storeAddress: 'Plot 42, Fergusson College Rd, Shivajinagar, Pune',
      locationName: 'Plot 42, Fergusson College Rd, Shivajinagar, Pune',
      latitude: 18.5255,
      longitude: 73.8595,
      phoneContact: '+91 98230 12345',
      productName: 'Artisan Sourdough Loaf',
      title: 'Artisan Sourdough Loaf',
      category: 'BAKERY',
      initialUnits: 15,
      remainingUnits: 15,
      soldUnits: 0,
      originalPrice: 120,
      recommendedPrice: 60,
      publishedPrice: 60,
      discountedPrice: 60,
      wasteRiskScore: 78,
      salesVelocity: 'LOW',
      deadline: new Date(now + 60 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 9:00 PM',
      status: 'ACTIVE',
      discountPct: 50,
      freshnessTag: 'Verified Fresh',
      description: 'Slow-fermented artisan rustic sourdough loaf. Baked fresh this morning.',
      imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 10 * 60000).toISOString(),
      updatedAt: new Date(now - 10 * 60000).toISOString(),
    },
    {
      id: 'deal-sandwich-2',
      storeId: 'store-abc-bakery',
      storeName: 'ABC Gourmet Bakery & Café',
      shopName: 'ABC Gourmet Bakery & Café',
      storeCategory: 'BAKERY',
      storeAddress: 'Plot 42, Fergusson College Rd, Shivajinagar, Pune',
      locationName: 'Plot 42, Fergusson College Rd, Shivajinagar, Pune',
      latitude: 18.5255,
      longitude: 73.8595,
      phoneContact: '+91 98230 12345',
      productName: 'Fresh Veggie Club Sandwich Combo',
      title: 'Fresh Veggie Club Sandwich Combo',
      category: 'BAKERY',
      initialUnits: 18,
      remainingUnits: 17,
      soldUnits: 1,
      originalPrice: 60,
      recommendedPrice: 40,
      publishedPrice: 40,
      discountedPrice: 40,
      wasteRiskScore: 68,
      salesVelocity: 'LOW',
      deadline: new Date(now + 50 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 5:30 PM - 8:30 PM',
      status: 'ACTIVE',
      discountPct: 33,
      freshnessTag: 'Verified Fresh',
      description: 'Triple decker multigrain bread, fresh lettuce, cheddar cheese, and garden cucumber.',
      imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 20 * 60000).toISOString(),
      updatedAt: new Date(now - 5 * 60000).toISOString(),
    },
    {
      id: 'deal-margherita-3',
      storeId: 'store-xyz-pizzeria',
      storeName: 'XYZ Campus Pizzeria & Deli',
      shopName: 'XYZ Campus Pizzeria & Deli',
      storeCategory: 'RESTAURANT',
      storeAddress: '12 University Circle, Model Colony, Pune',
      locationName: '12 University Circle, Model Colony, Pune',
      latitude: 18.5298,
      longitude: 73.8652,
      phoneContact: '+91 98220 54321',
      productName: 'Margherita Pizza Slice Duo',
      title: 'Margherita Pizza Slice Duo',
      category: 'RESTAURANT',
      initialUnits: 8,
      remainingUnits: 5,
      soldUnits: 3,
      originalPrice: 150,
      recommendedPrice: 90,
      publishedPrice: 90,
      discountedPrice: 90,
      wasteRiskScore: 64,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 130 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 7:00 PM - 10:30 PM',
      status: 'ACTIVE',
      discountPct: 40,
      freshnessTag: 'Warm Batch',
      description: 'Fresh San Marzano tomato base, buffalo mozzarella, and sweet garden basil.',
      imageUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 30 * 60000).toISOString(),
      updatedAt: new Date(now - 12 * 60000).toISOString(),
    },
    {
      id: 'deal-rice-bowl-4',
      storeId: 'store-green-canteen',
      storeName: 'The Green Campus Canteen',
      shopName: 'The Green Campus Canteen',
      storeCategory: 'CANTEEN',
      storeAddress: 'MIT-WPU Quadrangle, Kothrud, Pune',
      locationName: 'MIT-WPU Quadrangle, Kothrud, Pune',
      latitude: 18.5160,
      longitude: 73.8505,
      phoneContact: '+91 98210 99887',
      productName: 'Paneer Makhani Rice Bowl',
      title: 'Paneer Makhani Rice Bowl',
      category: 'CANTEEN',
      initialUnits: 12,
      remainingUnits: 6,
      soldUnits: 6,
      originalPrice: 110,
      recommendedPrice: 70,
      publishedPrice: 70,
      discountedPrice: 70,
      wasteRiskScore: 72,
      salesVelocity: 'HIGH',
      deadline: new Date(now + 40 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 5:00 PM - 8:00 PM',
      status: 'ACTIVE',
      discountPct: 36,
      freshnessTag: 'Kitchen Fresh',
      description: 'Fresh basmati rice bowl topped with cottage cheese cubes in spiced butter gravy.',
      imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 45 * 60000).toISOString(),
      updatedAt: new Date(now - 15 * 60000).toISOString(),
    },
    {
      id: 'deal-muffins-5',
      storeId: 'store-bean-brew',
      storeName: 'Bean & Brew Artisanal Coffee Bar',
      shopName: 'Bean & Brew Artisanal Coffee Bar',
      storeCategory: 'CAFE',
      storeAddress: '5 Lane 7, Koregaon Park, Pune',
      locationName: '5 Lane 7, Koregaon Park, Pune',
      latitude: 18.5340,
      longitude: 73.8610,
      phoneContact: '+91 98290 66778',
      productName: 'Blueberry & Chocochip Muffin Pair',
      title: 'Blueberry & Chocochip Muffin Pair',
      category: 'CAFE',
      initialUnits: 10,
      remainingUnits: 7,
      soldUnits: 3,
      originalPrice: 140,
      recommendedPrice: 80,
      publishedPrice: 80,
      discountedPrice: 80,
      wasteRiskScore: 52,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 110 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 7:00 PM - 10:30 PM',
      status: 'ACTIVE',
      discountPct: 43,
      freshnessTag: 'Verified Fresh',
      description: 'Moist oven-baked bakery muffins bursting with blueberries and dark chocolate chips.',
      imageUrl: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 25 * 60000).toISOString(),
      updatedAt: new Date(now - 25 * 60000).toISOString(),
    },
    {
      id: 'deal-fruit-6',
      storeId: 'store-freshmart',
      storeName: 'FreshMart Super Grocers',
      shopName: 'FreshMart Super Grocers',
      storeCategory: 'GROCERY',
      storeAddress: 'Shop 3, Deccan Gymkhana, Pune',
      locationName: 'Shop 3, Deccan Gymkhana, Pune',
      latitude: 18.5130,
      longitude: 73.8420,
      phoneContact: '+91 98244 33221',
      productName: 'Chilled Organic Seasonal Fruit Medley',
      title: 'Chilled Organic Seasonal Fruit Medley',
      category: 'GROCERY',
      initialUnits: 14,
      remainingUnits: 9,
      soldUnits: 5,
      originalPrice: 95,
      recommendedPrice: 55,
      publishedPrice: 55,
      discountedPrice: 55,
      wasteRiskScore: 58,
      salesVelocity: 'MEDIUM',
      deadline: new Date(now + 75 * 60 * 1000).toISOString(),
      pickupWindow: 'Today 6:00 PM - 9:30 PM',
      status: 'ACTIVE',
      discountPct: 42,
      freshnessTag: 'Chilled & Crisp',
      description: 'Pre-cut papaya, dragonfruit, kiwi, and pomegranate seeds in a sealed container.',
      imageUrl: 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=600&auto=format&fit=crop&q=80',
      image: 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?w=600&auto=format&fit=crop&q=80',
      createdAt: new Date(now - 35 * 60000).toISOString(),
      updatedAt: new Date(now - 35 * 60000).toISOString(),
    }
  ];
}